### ISSUE TITLE
Help text is not up to date

### ISSUE THREAD

**Issue by ayavilevich** [MoT3rror/egginc-coop-tracker#17]
![image](https://user-images.githubusercontent.com/1146791/106394012-eb942980-6402-11eb-9543-75268f15dbd1.png)

at least not for ``set-player-id`` command. Check that all are ok.

**Comment by MoT3rror** [comment]
I am going to rewrite the help command for this.

**Comment by ayavilevich** [comment]
@MoT3rror np, if you don't want me to do it just assign to yourself or close this.
I don't mind fixing the text now and you later doing a more complete solution later.
