### ISSUE TITLE
Add command to list players with their coop egg laying buffs

### ISSUE THREAD

**Issue by ayavilevich** [MoT3rror/egginc-coop-tracker#27]
Add a command to return what kind of coop buffs each team member has.
Mainly interested in the egg laying buff. Can also calc earning buff in case we want to show that in the future.

Example usage: "eb!TBD"

Output row for each player: name - rank - tach %

Output example:
UserA Mirror 10%
UserB Max 8%

-----------
Website alternative:

Change up the web version to default groupings as above, presort and add tach%

@MoT3rror fyi

**Comment by MoT3rror** [comment]
Added as another column to players command currently.
https://github.com/MoT3rror/egginc-coop-tracker/commit/eac3ea93384432b57b4371242798f99cd10f95ce#diff-2fff09e617c14621904de1baaabfc13e4d46ec8bec7d9d5585efbaed5e79c031R42

I May add it to the web but this function is not fast at all and this probably already slowed down the page.

**Comment by ayavilevich** [comment]
Great
